### ISSUE TITLE
Error with keep-alive packet

### ISSUE THREAD

**Issue by rienafairefr** [janispritzkau/minecraft-reverse-proxy#2]
I have some problems with using the project, the servers are version 1.9, and there is a problem when passing the packets apparently: 

events.js:170
      throw er; // Unhandled 'error' event
      ^

RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 2. Received 5
    at boundsError (internal/buffer.js:58:9)
    at Buffer.readUInt32BE (internal/buffer.js:205:5)
    at PacketReader.readUInt32 (/app/mcproto/lib/packet.js:49:28)
    at PacketReader.readUInt64 (/app/mcproto/lib/packet.js:56:34)
    at PacketReader.readInt64 (/app/mcproto/lib/packet.js:52:39)
    at onPacket.packet (/app/mcproto/lib/client.js:59:81)
    at on.packet (/app/mcproto/lib/connection.js:46:17)
    at forEach.cb (/app/mcproto/lib/events.js:35:37)
    at Array.forEach (<anonymous>)
    at Client.emit (/app/mcproto/lib/events.js:35:23)
Emitted 'error' event at:
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at Reader.onerror (_stream_readable.js:729:7)
    at Reader.emit (events.js:193:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)

When adding a `console.debug(packet)` inside mcproto onPacket :

PacketReader {
  buffer: <Buffer 1f 8f 81 9b 9f 03>,
  protocol: 107,
  offset: 1,
  id: 31 }

The problem happens on version 0.3.2, but not on version 0.2.5, if that helps

**Comment by janispritzkau** [comment]
Hi. I messed something up in this version. It was unrelated to the keep alive packet because the proxy normally wouldn't get to that point and instead directly pipe the tcp stream. It should work again now.
