### ISSUE TITLE
Crash when using invalid hostname / protocol

### ISSUE THREAD

**Issue by voyzark** [janispritzkau/minecraft-reverse-proxy#3]
When entering the wrong hostname or connecting with the wrong protocol (e.g. http) the proxy crashes:
```
/usr/share/minecraft-reverse-proxy/lib/index.js:65
        return setTimeout(() => conn.end(), 1000);
                                     ^

ReferenceError: conn is not defined
    at Timeout.setTimeout [as _onTimeout] (/usr/share/minecraft-reverse-proxy/lib/index.js:65:38)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
```

By looking at the surrounding code I would guess the line should be
```return setTimeout(() => client.end(), 1000);```

**Comment by janispritzkau** [comment]
Should be fixed now
